### ISSUE TITLE
[Feature] Intuitive API

### ISSUE THREAD

**Issue by Ordiel** [i-net-software/JWebAssembly-API#4]
I was checking the API for the project and, it is a bit verbose (in my humble opinion), and I consider it could be a bit more intuitive, for example check [j2html](https://github.com/tipsy/j2html)'s API.

I consider this project may benefit a lot from having a similar API. Furthermore, I would like to contribute, for such API changes. @Horcrux7 please let me know if this is something you have envisioned for this project or an addition which you consider would add value to it. If so, it would be nice if you could provide a CONTRIBUTE document that I can use. 

--- 
I gave it a try on my own, and I was able to build this project (The API one) using maven (`mvn install`  to get it on my local repo dir, having changed the version to 0.4.1), yet when I paired it with my POC (J)webassembly project, even when I added the `mavenLocal()` directive under my `repositories` block on my `build.gradle` and updated the version (to match the 0.4.1) I was unable to get my POC project identify my new version of the API.

Thanks in advance

**Comment by Horcrux7** [comment]
> I was checking the API for the project and, it is a bit verbose (in my humble opinion), and I consider it could be a bit more intuitive, for example check [j2html](https://github.com/tipsy/j2html)'s API.

The goal of this project is to create a very pure base API. And there is many missing because I work mostly on the compiler.

What you try look like: https://github.com/Eskerepvp/Jekt

> I consider this project may benefit a lot from having a similar API. Furthermore, I would like to contribute, for such API changes. @Horcrux7 please let me know if this is something you have envisioned for this project or an addition which you consider would add value to it. If so, it would be nice if you could provide a CONTRIBUTE document that I can use.

Any contribution is very welcome. There are many ToDo. For example, to open a connection to a server via an Ajax request in JavaScript, but in Java with an HttpUrlConnection.

If you want to write a higher level API, then I think that should be a separate project. But I am not sure. If you want to start such a project I can link it here.

> I gave it a try on my own, and I was able to build this project (The API one) using maven (mvn install to get it on my local repo dir, having changed the version to 0.4.1), yet when I paired it with my POC (J)webassembly project, even when I added the mavenLocal() directive under my repositories block on my build.gradle and updated the version (to match the 0.4.1) I was unable to get my POC project identify my new version of the API.

Do you have run the Gradle task `publishToMavenLocal` to push it to the maven repository? For the API I use this simpler solution. This is the output directory from my IDE.

```
dependencies {
    implementation files( 'C:/workspace/JWebAssembly-API/bin/main' );
}
```
Another causes can be:

- running Gradle daemon that has already load the Classes. Kill the Gradle daemon
- If you does not change the build script or the sources then for Gradle is all UPTODATE. Clear the output directory.

**Comment by Ordiel** [comment]
Thanks, I've been looking into it and your approach makes sense. Closing
